public enum StatusChange {
    ATTACK, SPECIAL_ATTACK, DEFENSE, SPECIAL_DEFENSE, SPEED, HEALTH, ACCURACY, EVASIVENESS,
    INFLICT_POISON, INFLICT_BURN, INFLICT_SLEEP, INFLICT_CONFUSION, INFLICT_PARALYSIS, FREEZE;
}